### ISSUE TITLE
Non-native JS syntax and flags don't seem to work

### ISSUE THREAD

**Issue by slevithan** [regexplanet/regexplanet-xregexp#2]
The page at http://www.regexplanet.com/advanced/xregexp/ seems to only work if given native JS regex syntax. Any XRegExp-specific features don't seem to work.

Following are a few examples I tried:

Regex: `a a`
Flags: `x`
Input: `aa`
Result: No match found (regex.exec shows null)
Expected: Should match `aa`

Regex: `(?<name>.)`
Result: Error (unable to create RegExp object)
Expected: This is valid XRegExp syntax

Regex: `(?#comment)`
Result: Error (unable to create RegExp object)
Expected: This is valid XRegExp syntax

Regex: `\a`
Input: `a`
Result: Match found
Expected: Should be an error

**Comment by fileformat** [comment]
Fixed.  It was looking at the wrong server.

**Comment by slevithan** [comment]
:+1:  Thanks for the quick fix!
